//Values are measured in billions of pounds

var json_data = {"Parliamentary Counsel Office (PCO)": "0.009",
                 "DWP!A1": "166.979",
                 "Total public service pensions": "8.4",
                 "Independent Safeguarding Authority (ISA)": "0.013",
                 "HM Treasury (exc financial stability)": "0.228",
                 "Office of the Immigration Service Commissioner (OISC)": "0.004",
                 "Security Industry Authority (SIA)": "0.028",
                 "Attorney General's Office (see also LSLO)": "0.004",
                 "DCMS!A1": "7.624",
                 "Treasury Solicitors' Department": "-0.002",
                 "'CABINET%20OFFICE'!A1": "0.461",
                 "UK Sport": "0.068",
                 "DEFRA!A1": "2.331",
                 "DCLG!A1": "32.727",
                 "Office of Qualifications and Examinations Regulation (OFQUAL)": "0.016",
                 "Independent Police Complaints Commission (IPCC)": "0.033",
                 "NIO!A1": "0.022",
                 "Sport England ": "0.105",
                 "WALES!A1": "15.003",
                 "HMRC!A1": "46.585",
                 "VisitBritain": "0.05",
                 "Olympic Delivery Authority": "0.074",
                 "Scotland Office (SO)": "0.021",
                 "UK Trade & Investment (UKTI)": "0.082",
                 "National Audit Office": "0.07",
                 "Crown Prosecution Service (CPS)": "0.589",
                 "Water Services Regulation Authority (Ofwat)": "0.019",
                 "Office of Communications (Ofcomm) from government funding (rest from license fees)": "0.109",
                 "HM Crown Prosecution Service Inspectorate": "0.004",
                 "Independent Parliamentary Standards Authority": "0.146",
                 "Creative Scotland": "0.076",
                 "Health Protection Agency": "0.161",
                 "DEPARTMENT": "2011/12, \u00a3bn",
                 "House of Lords": "0.109",
                 "Wales Office (WO)": "0.005",
                 "TOTAL EXPENDITURE": "694.888",
                 "House of Commons": "0.23",
                 "Security and intelligence services": "1.987",
                 "Government Actuary's Department (GAD)": "-0.002",
                 "DFID!A1": "7.873",
                 "DFE!A1": "56.269",
                 "BIS!A1": "21.336",
                 "SCOTLAND!A1": "33.524",
                 "National Lottery Commission (running costs)": "0.005",
                 "Electoral Commission": "0.086",
                 "MOD!A1": "37.249",
                 "FCO!A1": "2.195",
                 "Arts Council England": "0.461",
                 "Office for Standards in Education (OFSTED)": "0.166",
                 "Equality & Human Rights Commission": "0.043",
                 "National Policing Improvement Agency (NPIA)": "0.364",
                 "Office of Fair Trading (OFT)": "0.062",
                 "European Union": "6.967",
                 "Serious Organised Crime Agency (SOCA)": "0.465",
                 "National Savings and Investments": "0.174",
                 "National Lottery Commission (funds distribution)": "1.813",
                 "English Heritage": "0.17",
                 "Arts Council Wales": "0.036",
                 "DoH!A1": "106.659",
                 "DfT!A1": "12.735",
                 "UK Statistics Authority": "0.325",
                 "Financial Services Authority": "0.492",
                 "Debt interest payments": "48.2",
                 "Serious Fraud Office (SFO)": "0.03",
                 "Office of Rail Regulation (ORR)": "0.029",
                 "Food Standards Agency": "0.089",
                 "HO!A1": "10.097",
                 "DECC!A1": "6.12",
                 "Office of Gas and Electricity Markets/Gas and Electricity Markets Authority (OFGEM)": "0.00067",
                 "HEFCE (BIS)": "6.843",
                 "Charity Commission for England and Wales": "0.027",
                 "MoJ!A1": "8.551",
                 "Office for Budget Responsibility": "0.002",
                 "NI!A1": "10.329"}
